services:
  - type: web
    name: mk-hub-api
    env: docker
    plan: starter
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: AUTO_CREATE_DB
        value: "true"
      - key: DATABASE_URL
        value: "sqlite:////opt/render/project/src/var/prod.db"
      - key: PUBLIC_BASE_URL
        value: "https://mkhub2.onrender.com"
      - key: MAIL_FROM
        value: "noreply@mackkirk.com"
      - key: SMTP_HOST
        value: "smtp.sendgrid.net"
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USERNAME
        value: "apikey"
      - key: SMTP_PASSWORD
        sync: false
      - key: ADMIN_USERNAME
        value: "admin"
      - key: ADMIN_EMAIL
        value: "admin@example.com"
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: TZ_DEFAULT
        value: "America/Vancouver"
    disk:
      name: data
      mountPath: /opt/render/project/src/var
      sizeGB: 1

